import { useEffect, useState, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import API from '../services/api';
import Navbar from '../components/Navbar';
import { Link } from 'react-router-dom';

const QuizCard = ({ quiz, user, handleDelete, showCreator }) => (
  <div className="col-md-4 mb-4" key={quiz._id}>
    <div className="card h-100 shadow-sm border-0 rounded-3">
      <div className="card-body d-flex flex-column">
        <h5 className="card-title fw-bold text-primary">{quiz.title}</h5>
        <p className="card-text text-muted small flex-grow-1">{quiz.description}</p>
        
        {showCreator && quiz.createdBy && quiz.createdBy.role !== 'admin' && (
          <div className="mb-3">
            <span className="badge bg-info text-dark shadow-sm">Generated by: {quiz.createdBy.name || 'Student'}</span>
          </div>
        )}

        <div className="d-flex justify-content-between align-items-center mt-auto pt-1">
          <span className="badge bg-secondary">{quiz.timeLimit} Mins</span>
          <div className="d-flex gap-2">
            {(user?.role === 'admin' || (quiz.createdBy && quiz.createdBy._id === user?._id)) && (
              <button onClick={() => handleDelete(quiz._id)} className="btn btn-danger btn-sm px-3 fw-bold">Delete</button>
            )}
            <Link to={`/quiz/${quiz._id}`} className="btn btn-primary btn-sm px-4 fw-bold">Start</Link>
          </div>
        </div>
      </div>
    </div>
  </div>
);

const QuizList = () => {
  const [quizzes, setQuizzes] = useState([]);
  const [filter, setFilter] = useState('all');
  const { user } = useContext(AuthContext);

  const filteredQuizzes = quizzes.filter(quiz => {
    if (filter === 'all') return true;
    if (filter === 'admin') return (!quiz.createdBy || quiz.createdBy.role === 'admin');
    if (filter === 'me') return (quiz.createdBy && quiz.createdBy._id === user?._id);
    return true;
  });

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this quiz?")) {
      try {
        await API.delete(`/quizzes/${id}`);
        setQuizzes(quizzes.filter(quiz => quiz._id !== id));
      } catch (error) {
        console.error("Failed to delete quiz", error);
        alert("Failed to delete quiz");
      }
    }
  };

  useEffect(() => {
    const fetchQuizzes = async () => {
      try {
        const { data } = await API.get('/quizzes');
        setQuizzes(data);
      } catch (err) {
        console.error("Error fetching quizzes", err);
      }
    };
    fetchQuizzes();
  }, []);

  const adminQuizzes = quizzes.filter(q => !q.createdBy || q.createdBy.role === 'admin');
  const studentQuizzes = quizzes.filter(q => q.createdBy && q.createdBy.role !== 'admin');

  return (
    <>
      <Navbar />
      <div className="container mt-5">
        <div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-3">
          <h2 className="fw-bold mb-0">Available Assessments</h2>
          {user?.role !== 'admin' && (
            <div className="btn-group shadow-sm" role="group">
              <button 
                className={`btn ${filter === 'all' ? 'btn-primary' : 'btn-outline-primary'} text-white fw-bold px-3`}
                onClick={() => setFilter('all')}
              >
                All
              </button>
              <button 
                className={`btn ${filter === 'admin' ? 'btn-primary' : 'btn-outline-primary'} text-white fw-bold px-3`}
                onClick={() => setFilter('admin')}
              >
                Official
              </button>
              <button 
                className={`btn ${filter === 'me' ? 'btn-primary' : 'btn-outline-primary'} text-white fw-bold px-3`}
                onClick={() => setFilter('me')}
              >
                My Quizzes
              </button>
            </div>
          )}
        </div>

        {user?.role === 'admin' ? (
          <>
            <h4 className="mt-4 mb-3 text-white fw-bold border-bottom pb-2">Official Quizzes</h4>
            <div className="row">
              {adminQuizzes.length > 0 ? (
                adminQuizzes.map((quiz) => (
                  <QuizCard key={quiz._id} quiz={quiz} user={user} handleDelete={handleDelete} showCreator={false} />
                ))
              ) : (
                <div className="col-12"><p className="text-muted">No official quizzes found.</p></div>
              )}
            </div>

            <h4 className="mt-5 mb-3 text-white fw-bold border-bottom pb-2">Student Generated Quizzes</h4>
            <div className="row">
              {studentQuizzes.length > 0 ? (
                studentQuizzes.map((quiz) => (
                  <QuizCard key={quiz._id} quiz={quiz} user={user} handleDelete={handleDelete} showCreator={true} />
                ))
              ) : (
                <div className="col-12"><p className="text-muted">No student generated quizzes found.</p></div>
              )}
            </div>
          </>
        ) : (
          <div className="row">
            {filteredQuizzes.length > 0 ? (
              filteredQuizzes.map((quiz) => (
                <QuizCard key={quiz._id} quiz={quiz} user={user} handleDelete={handleDelete} showCreator={false} />
              ))
            ) : (
              <div className="col-12"><p className="text-muted">No quizzes available in this category.</p></div>
            )}
          </div>
        )}
      </div>
    </>
  );
};

export default QuizList;